### ISSUE TITLE
This project lacks a README.md file with instructions 

### ISSUE THREAD

**Issue by sviscapi** [VonTum/Dedekind#1]
Dear Lennart @VonTum ,

Could you please add some README.md to this project, with instructions on how to build your code ?

So far my compilation attempts fail with the following error message:

    /home/samuel/src/Dedekind/fpga_production/fpgaBoilerplate.cpp:3:10: fatal error: CL/cl_ext_intelfpga.h: No such file or directory
    3 | #include <CL/cl_ext_intelfpga.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~

Is your application only compatible with FPGA ? Should I install the missing headers, even though I plan to compile your code for x86_64 ?

Best regards,

Samuel

**Comment by VonTum** [comment]
Hi Samuel, 

Yes, those headers are for the Intel OpenCL FPGA connection. I've split up the repository into two main artifacts: production and fpga_production. production does not depend on anything FPGA related, and contains optimized x86 code for computing the parts. fpga_production contains the code to interface with the prebuilt FPGA kernel. This kernel is not built as part of the CMake, as it takes about half a day on our 128-core system. If you want I can send over the built kernel for the N520 card. 

You should be able to compile production separately, with CMake it should do that already, even if fpga_production errors.

**Comment by sviscapi** [comment]
Hi Lennart. Thanks for adding a README file to your project. Regards, Samuel
